### ISSUE TITLE
iot-edge-sdk-for-iot-parser/modbus/bin/linux_arm/ 能在树莓派上运行吗

### ISSUE THREAD

**Issue by xwdreamer** [baidu/iot-edge-sdk-for-iot-parser#8]
运行./bdModbusGateway程序，提示”Segmentation fault”，如下图所示。

![image](https://user-images.githubusercontent.com/1173919/52936397-f29d0b00-3396-11e9-9dc7-48cbe905e9af.png)

**Comment by xwdreamer** [comment]
补充树莓派信息
`
pi@raspberrypi:~ $ cat  /proc/version
Linux version 4.14.79-v7+ (dc4@dc4-XPS13-9333) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611)) #1159 SMP Sun Nov 4 17:50:20 GMT 2018

pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux
`

![image](https://user-images.githubusercontent.com/1173919/52940685-144fbf80-33a2-11e9-9393-0501e749494a.png)

**Comment by ubyyj** [comment]
需要用树莓派的编译环境，对源代码进行重新编译。编译脚本请参考cross_compile下面的例子。
现在提供的arm版本并不能适用于所有的硬件。

**Comment by xwdreamer** [comment]
> 需要用树莓派的编译环境，对源代码进行重新编译。编译脚本请参考cross_compile下面的例子。
> 现在提供的arm版本并不能适用于所有的硬件。

树莓派其实是常用的一个平台，能付提供针对树莓派的编译脚本，同时也给出树莓派的执行程序。

**Comment by ubyyj** [comment]
谢谢你的反馈，我们会认真考虑你的建议。同时请你关注我们的产品，以便及时得到后续更新的通知。

**Comment by xwdreamer** [comment]
1.先按照这个教程在ubuntu上搭建树莓派的交叉编译环境。http://geomodule.com/sw-eng-notes/2017/03/25/raspberry-pi-cross-compiling/
2.然后在ubuntu上git clone本项目，到iot-edge-sdk-for-iot-parser/modbus/cross-compile/目录下，执行linux-arm.sh。
3.执行成功以后，在bin目录下生成对应的可执行程序。将iot-edge-sdk-for-iot-parser/modbus/bin/linux_arm/目录下的bdModbusGateway拷贝到树莓派下，执行程序
4.成功
![image](https://user-images.githubusercontent.com/1173919/52999699-6d325d00-3461-11e9-9e09-aafc08478915.png)

**Comment by ubyyj** [comment]
非常感谢你的分享!
