### ISSUE TITLE
diagslave是否可以模拟指定数据

### ISSUE THREAD

**Issue by xwdreamer** [baidu/iot-edge-sdk-for-iot-parser#9]
@ubyyj 
观看你的官方教程：https://cloud.baidu.com/doc/Parser/GUIGettingStarted.html#.1C.CB.49.22.10.1B.B7.FA.F2.61.52.E7.F2.8D.F3.83
发现你用到了diagslave，但是这个diagslave出来的值都是0，这样模拟效果不是很好。
diagsalve是否可以指定特定的值，然后让bdModbusGateway采集到。

**Comment by ubyyj** [comment]
可以，你可以写diagslave(比如，你用网关的反控主题发送反控指令，讲寄存器中的数据改成非0)

**Comment by xwdreamer** [comment]
确实可行，如下图，value确实不再为0
![image](https://user-images.githubusercontent.com/1173919/53072022-df1cac00-351e-11e9-85ab-0f81f3458a8d.png)

我原先用的是modsim32.exe这样的slave模拟器，这个软件可以自定义40001这个寄存器的值，还可以是随机值。所以我是在想diagslave是否也有你这样的功能。
现在看下来，应该是bdModbusGateway实现了写modbus寄存器的能力，可以通过backcontrol topic从上往下写数据，而不是diagslave自身变数据。
